# VERSION:        0.1
# DESCRIPTION:    Create a container with ungit installed
# AUTHOR:         ptt-homme <tomcreaweb@gmail.com>
# COMMENTS:
#  	NC
# USAGE:
#
#   # Build Composer image
#   docker build -t youralias/image .
#

# Base Docker image.
FROM node:0.12.7

MAINTAINER ptt-homme <tomcreaweb@gmail.com>

# Install ungit.
RUN npm install -g ungit
